"use server";

export const createBatch = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const updateBatch = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const deleteBatch = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const createLanguageCourseAction = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const createCourse = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const updateCourse = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const deleteCourse = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const createTeacher = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const updateTeacher = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const deleteTeacher = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const revokeCertificateAction = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const deleteCertificateAction = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const issueCertificate = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const fetchEnrollments = async (...args: any[]): Promise<any> => { return []; };
export const sendPaymentReminderAction = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const deleteEnrollment = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const updateEnrollment = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const assignBatchToEnrollmentAction = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const confirmEnrollmentPaymentAction = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const fetchAvailableBatches = async (...args: any[]): Promise<any> => { return []; };
export const requestTeacherWithdrawalAction = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
export const updateTeacherEarningPaymentAction = async (...args: any[]): Promise<any> => { throw new Error("Not implemented"); };
