import "server-only";
import { runAgent } from "./runtime";
import { DraftSectionSchema, type DraftSection } from "./contracts";
import { REPORT_SYSTEM_PROMPT, REPORT_PROMPT_VERSION, buildReportUserPrompt } from "./prompts/report.v1";

/** Deterministic mock — echoes the source into a skeleton draft with an editor note. */
function mockDraft(section: string, sources: string): DraftSection {
  const trimmed = sources.replace(/\s+/g, " ").trim();
  const thin = trimmed.length < 200;
  return {
    section,
    markdown: `## ${section}\n\n${trimmed ? trimmed.slice(0, 600) : "[No source material provided.]"}\n`,
    editorNotes: thin
      ? [`[Note: source material for "${section}" was thin — this mock draft needs real content and review.]`]
      : [`[Note: generated by the deterministic mock writer — replace with an AI-drafted version before submission.]`],
    sourceRefs: [],
  };
}

/** Persona 4: draft one deliverable section grounded strictly in the provided sources. */
export async function draftSection(section: string, sources: string, contextRef?: string): Promise<{ draft: DraftSection; provider: string; runId: string }> {
  const { data, provider, runId } = await runAgent<DraftSection>({
    persona: "report",
    promptVersion: REPORT_PROMPT_VERSION,
    system: REPORT_SYSTEM_PROMPT,
    user: buildReportUserPrompt(section, sources),
    schema: DraftSectionSchema,
    mock: () => mockDraft(section, sources),
    contextRef,
  });
  return { draft: data, provider, runId };
}
